/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#003920",
        "surface-dim": "#0c1322",
        "on-secondary-fixed": "#2e1500",
        "secondary-container": "#d7790d",
        "primary-fixed": "#7df4ff",
        "inverse-surface": "#dce2f8",
        "inverse-on-surface": "#293041",
        "on-surface-variant": "#b9cacb",
        "primary": "#dbfcff",
        "on-primary-container": "#006970",
        "outline": "#849495",
        "tertiary-fixed-dim": "#00e38f",
        "surface-container-high": "#232a3a",
        "secondary-fixed": "#ffdcc2",
        "surface-variant": "#2e3545",
        "on-secondary-container": "#432100",
        "surface-container-low": "#141b2b",
        "primary-fixed-dim": "#00dbe9",
        "surface": "#0c1322",
        "background": "#0c1322",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#002111",
        "surface-bright": "#32394a",
        "on-background": "#dce2f8",
        "on-primary": "#00363a",
        "secondary-fixed-dim": "#ffb77a",
        "on-error": "#690005",
        "tertiary": "#daffe4",
        "surface-container-lowest": "#070e1d",
        "inverse-primary": "#006970",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004f54",
        "surface-tint": "#00dbe9",
        "primary-container": "#00f0ff",
        "error-container": "#93000a",
        "outline-variant": "#3b494b",
        "tertiary-container": "#11f89e",
        "on-tertiary-container": "#006d42",
        "on-secondary-fixed-variant": "#6d3a00",
        "on-primary-fixed": "#002022",
        "on-tertiary-fixed-variant": "#005231",
        "on-secondary": "#4c2700",
        "surface-container": "#181f2f",
        "secondary": "#ffb77a",
        "on-surface": "#dce2f8",
        "surface-container-highest": "#2e3545",
        "tertiary-fixed": "#53ffab",
        space: {
          950: '#070e1d',
          900: '#0c1322',
          850: '#141b2b',
          800: '#181f2f',
          700: '#232a3a',
          600: '#2e3545',
        },
        hud: {
          cyan: '#7df4ff',
          blue: '#00dbe9',
          amber: '#ffb77a',
          rose: '#ffb4ab',
          emerald: '#53ffab',
          saffron: '#d7790d',
        }
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "headline-display": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
