"use client";

import React, { useState } from "react";
import { X, Sparkles, Download, Share2, ArrowUpRight, Maximize2, Tag } from "lucide-react";

interface GalleryItem {
  id: string;
  title: string;
  mission: string;
  tag: string;
  imageUrl: string;
  prompt: string;
  resolution: string;
  author: string;
}

const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: "bas_station_01",
    title: "Bharatiya Antariksh Station in 400km Orbit",
    mission: "BAS & Gaganyaan",
    tag: "Space Station",
    imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=85&w=1200&auto=format&fit=crop",
    prompt: "generate image of the future Bharatiya Antariksh Station modular space habitat orbiting Earth with docking port connecting Gaganyaan crew capsule",
    resolution: "1920x1080 Full HD",
    author: "Stackverse-labs",
  },
  {
    id: "chandrayaan_01",
    title: "Chandrayaan-3 Vikram & Pragyan at Shiv Shakti",
    mission: "Chandrayaan-3",
    tag: "Chandrayaan",
    imageUrl: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=85&w=1200&auto=format&fit=crop",
    prompt: "generate image of Chandrayaan-3 Vikram lander on the moon south pole with Pragyan rover leaving wheel tracks on the grey regolith dust",
    resolution: "1920x1080 Full HD",
    author: "Omkar Bhandari",
  },
  {
    id: "aditya_01",
    title: "Aditya-L1 Halo Orbit Coronagraph",
    mission: "Aditya-L1",
    tag: "Aditya-L1",
    imageUrl: "https://images.unsplash.com/photo-1532693322450-2cb5c511067d?q=85&w=1200&auto=format&fit=crop",
    prompt: "generate image of ISRO Aditya-L1 solar observatory satellite in deep space halo orbit at Sun-Earth L1 facing coronal mass ejection",
    resolution: "1920x1080 Full HD",
    author: "DSU Research",
  },
  {
    id: "gaganyaan_01",
    title: "Gaganyaan Crew Module Orbital Sunrise",
    mission: "Gaganyaan",
    tag: "Gaganyaan",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=85&w=1200&auto=format&fit=crop",
    prompt: "generate image of ISRO Gaganyaan crew module spacecraft in low Earth orbit at orbital sunrise above the Himalayas",
    resolution: "1920x1080 Full HD",
    author: "Stackverse Community",
  },
  {
    id: "mars_01",
    title: "Mangalyaan Above Valles Marineris",
    mission: "Mars Orbiter",
    tag: "Mars",
    imageUrl: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?q=85&w=1200&auto=format&fit=crop",
    prompt: "generate image of ISRO Mangalyaan spacecraft soaring above the giant rust-red Valles Marineris canyon on Mars",
    resolution: "1920x1080 Full HD",
    author: "Stackverse-labs",
  },
];

interface CommunityGalleryModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectPrompt: (prompt: string) => void;
  onShareItem: (title: string, text: string, imageUrl: string) => void;
}

export default function CommunityGalleryModal({
  isOpen,
  onClose,
  onSelectPrompt,
  onShareItem,
}: CommunityGalleryModalProps) {
  const [selectedTag, setSelectedTag] = useState("All");
  const [activeItem, setActiveItem] = useState<GalleryItem | null>(null);

  if (!isOpen) return null;

  const tags = ["All", "Space Station", "Chandrayaan", "Gaganyaan", "Aditya-L1", "Mars"];
  const filtered = selectedTag === "All" ? GALLERY_ITEMS : GALLERY_ITEMS.filter((item) => item.tag === selectedTag);

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-md animate-fadeIn"
      onClick={onClose}
    >
      <div 
        className="relative w-full max-w-5xl h-[90vh] bg-[#0c1322] border border-slate-800 rounded-3xl shadow-2xl shadow-cyan-950/40 text-slate-100 flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="p-4 sm:p-6 border-b border-slate-800 flex items-center justify-between bg-slate-900/50">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-2xl bg-gradient-to-tr from-cyan-400 to-blue-600 flex items-center justify-center text-slate-950 shadow-md shadow-cyan-500/20">
              <Sparkles className="w-5 h-5 stroke-[2.5]" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-bold text-white tracking-tight">Community Space Gallery</h3>
                <span className="px-2 py-0.5 rounded-full text-[9px] font-mono font-bold bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
                  8K Renders
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Curated photorealistic astrophotography generated by AntarikshaVaani researchers
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tag Filters */}
        <div className="px-4 sm:px-6 py-3 border-b border-slate-800/80 flex items-center gap-1.5 overflow-x-auto custom-scrollbar bg-slate-950/40">
          {tags.map((tag) => (
            <button
              key={tag}
              onClick={() => setSelectedTag(tag)}
              className={`px-3 py-1 rounded-xl text-xs font-mono transition-all shrink-0 ${
                selectedTag === tag
                  ? "bg-cyan-500 text-slate-950 font-bold shadow-sm shadow-cyan-500/20"
                  : "bg-slate-900 text-slate-400 hover:text-white hover:bg-slate-800 border border-slate-800"
              }`}
            >
              {tag}
            </button>
          ))}
        </div>

        {/* Gallery Grid */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 custom-scrollbar">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {filtered.map((item) => (
              <div
                key={item.id}
                className="group relative rounded-2xl bg-slate-900/80 border border-slate-800 hover:border-cyan-500/40 transition-all overflow-hidden flex flex-col shadow-md"
              >
                {/* Image Viewport */}
                <div className="relative aspect-video w-full overflow-hidden bg-slate-950">
                  <img
                    src={item.imageUrl}
                    alt={item.title}
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                  <div className="absolute top-2.5 right-2.5 flex items-center gap-1.5">
                    <span className="px-2 py-0.5 rounded-md text-[9px] font-mono font-bold bg-black/70 backdrop-blur-md text-cyan-300 border border-slate-700">
                      {item.tag}
                    </span>
                  </div>
                </div>

                {/* Card Content */}
                <div className="p-4 flex-1 flex flex-col justify-between space-y-3">
                  <div>
                    <h4 className="text-xs font-bold text-white group-hover:text-cyan-300 transition-colors">
                      {item.title}
                    </h4>
                    <p className="text-[10px] font-mono text-slate-500 mt-0.5">
                      By {item.author} • {item.resolution}
                    </p>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center gap-2 pt-2 border-t border-slate-800/80">
                    <button
                      onClick={() => {
                        onSelectPrompt(item.prompt);
                        onClose();
                      }}
                      className="flex-1 flex items-center justify-center gap-1 px-3 py-1.5 rounded-xl bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/30 text-xs font-mono font-bold transition-all group-hover:bg-cyan-500 group-hover:text-slate-950"
                      title="Run this prompt in chat"
                    >
                      <span>Try Prompt</span>
                      <ArrowUpRight className="w-3.5 h-3.5" />
                    </button>

                    <button
                      onClick={() => onShareItem(item.title, item.prompt, item.imageUrl)}
                      className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors border border-slate-700"
                      title="Share to LinkedIn / Twitter / WhatsApp"
                    >
                      <Share2 className="w-3.5 h-3.5" />
                    </button>

                    <a
                      href={item.imageUrl}
                      download={`${item.id}.jpg`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="p-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors border border-slate-700"
                      title="Download image"
                    >
                      <Download className="w-3.5 h-3.5" />
                    </a>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
